### ISSUE TITLE
Add option to load new data

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora-postcorrect-app#12]
- [ ] Corpus data
- [x] Allowed Lemma
- [x] Allowed POS
- [x] Allowed morph

**Comment by PonteIneptique** [comment]
Partially fixed by #29 

Do you think editing corpus data should be possible @Jean-Baptiste-Camps ? I have my doubts about this...

**Comment by Jean-Baptiste-Camps** [comment]
I'm hesitant as well. It is useful in the real world of production, but, on the other hand, it risks messing with history. Might be cleaner to force recreating a corpus.
