### ISSUE TITLE
Create a Morph corpus for test

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora-postcorrect-app#20]
In the form of a wiki page, could you help me in building a morph corpus test ?

So if I take you original data 

```
escoutez	escouter	VERcjg	imp||2|p|||
amis	ami	NOMcom	|||s|m|n|
```

You would have (Definitely not sure if correct)

```tsv
label	readable
imp||2|p|||	Imperatif 2eme personne présent
|||s|m|n|	Nom Sujet Masculin
```

Could you do that for me ?

(on a related matter : I like the system built by Perseus for morphotagging such as `p-s---mn-` (Described down in https://github.com/gcelano/LemmatizedAncientGreekXML )

**Comment by Jean-Baptiste-Camps** [comment]
You mean, like in the CATTEX documentation ? 

http://bfm.ens-lyon.fr/IMG/pdf/Cattex2009_2.0.pdf

Or in the TEI version I worked on: 
https://github.com/Jean-Baptiste-Camps/Geste/blob/master/xml/appendix_cattex2009.xml

**Comment by PonteIneptique** [comment]
Yes but as full joined string and CSV :)

**Comment by Jean-Baptiste-Camps** [comment]
I can do that, when do you need it ?

**Comment by PonteIneptique** [comment]
There is no time pressure, though this is something I need to develop a little more the morph function (Which is a little different from lemma and POS). #18 is definitely more important :)

**Comment by PonteIneptique** [comment]
You should write in the wiki, in the form of a TSV following the title I used in https://github.com/hipster-philology/pandora-postcorrect-app/wiki

**Comment by PonteIneptique** [comment]
If you feel like you have some time to throw into this app, you could write, in the branche issue-18, fixtures like the one in https://github.com/hipster-philology/pandora-postcorrect-app/blob/master/tests/db_fixtures.py and https://github.com/hipster-philology/pandora-postcorrect-app/blob/master/tests/fixtures.py (in the same files).

I find sublime super useful to write these :) You could save me half an hour :D

**Comment by Jean-Baptiste-Camps** [comment]
Ok, I have added a page to the wiki with the current state of morph labels (I keep thinking about modifying them…). 
Here it is: https://github.com/hipster-philology/pandora-postcorrect-app/wiki/FRO-:-List-of-allowed-morph-%5BCattex2009_max-simplifi%C3%A9%5D

**Comment by PonteIneptique** [comment]
Could you potentially take the time to generate fixtures in db_fixtures and fixtures ? 

it should be 
```python
Morph = [
    AllowedMorph(corpus=2, label="NOM=....", readable="singuler...")
]
```

**Comment by PonteIneptique** [comment]
(And thanks !)

**Comment by Jean-Baptiste-Camps** [comment]
Sure, but, to do that, I need to modify my whole XSL transformation workflow again, to adapt it to the new way of expressing morph. And possibly re-edit it later to accommodate yet another (and cleaner) way of describing them. Right now, Floovant morph labels don't match the ones in the list of allowed labels. This will take a little more time.

**Comment by PonteIneptique** [comment]
Don't mind then. With a csv and some sublime or libre office, you can do
that quite well and more quickly than a xsl :')
This is just some dummy, I don't need them to be here always

Le 18 oct. 2017 11:14 AM, "Jean-Baptiste-Camps" <notifications@github.com>
a écrit :

Sure, but, to do that, I need to modify my whole XSL transformation
workflow again, to adapt it to the new way of expressing morph. And
possibly re-edit it later to accommodate yet another (and cleaner) way of
describing them. Right now, Floovant morph labels don't match the ones in
the list of allowed labels. This will take a little more time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hipster-philology/pandora-postcorrect-app/issues/20#issuecomment-337518183>,
or mute the thread

**Comment by Jean-Baptiste-Camps** [comment]
But I need to modify it anyway. I'm working on it now.

**Comment by Jean-Baptiste-Camps** [comment]
And I don't think that I can do my full workflow better with Sublime than with XSLT ;)

**Comment by PonteIneptique** [comment]
I just meant creating the test corpus. Not the rest of it :)

**Comment by Jean-Baptiste-Camps** [comment]
There you have it.
