### ISSUE TITLE
Find similar cases for lines that were not changed

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pandora-postcorrect-app#23]
It could be interesting to have a function, when a line is saved without editing it's values, to find similar cases without the same annotation. It would be another way to mass correct, in parallel to the one currently implemented.

**Comment by PonteIneptique** [comment]
eg.
Rechercher toutes les lignes où la forme est similaire mais pas le lemme.
Rechercher toutes les lignes où la forme est similaire mais pas la POS.
Rechercher toutes les lignes où la forme est similaire mais pas la morph.

**Comment by PonteIneptique** [comment]
Here is a preview : 
![screenshot-localhost 5000-2017-10-09-18-08-34](https://user-images.githubusercontent.com/1929830/31347528-eddf357c-ad1c-11e7-920e-a9f3bee5324b.png)
![screenshot-localhost 5000-2017-10-09-17-59-16](https://user-images.githubusercontent.com/1929830/31347530-ee8229b2-ad1c-11e7-854e-3359b593cc0e.png)

**Comment by PonteIneptique** [comment]
Does the UI fits your needs ? I put the partial similar count (form that shares at least the form and one of the three editable value : lemma, POS or morph)

**Comment by PonteIneptique** [comment]
I could add an except (all the same except lemma, all the same except morph) as stated in the original issue though.

**Comment by Jean-Baptiste-Camps** [comment]
Yes, that would be great too, and the UI is very convenient.

**Comment by PonteIneptique** [comment]
I just need to write tests for this thing, both on the mode side and the editing side.

**Comment by PonteIneptique** [comment]
Fix in the PR.

**Comment by PonteIneptique** [comment]
Fixed by #26 :)
