### ISSUE TITLE
Autocompletion not working for lemmas with accentuated characters

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pandora-postcorrect-app#32]
Apparently, the PPA cannot autocomplete lemmas such as "öir", "pöoir", etc. It may be a problem with unicode normalisation (combine, not combine).

**Comment by PonteIneptique** [comment]
This is a weird one, because it should be using the normalized. Can you try to track the issue ?

**Comment by Jean-Baptiste-Camps** [comment]
Happens with 'é' as well.

**Comment by Jean-Baptiste-Camps** [comment]
But there are 4 differents kinds of unicode normalisation. So, my first hypothesis was that the user input `o+^` did not fit the normalised combined version of database. But it does not makes sense with `é`.

**Comment by Jean-Baptiste-Camps** [comment]
Correction: ça marche si on ne tape pas les caractères accentués (il trouve l'équivalent avec accent…).

**Comment by PonteIneptique** [comment]
Ok, donc le bug est dans l'input de recherche et non dans les données recherchées.
Facile à corriger :)

**Comment by PonteIneptique** [comment]
YAYYYY
