### ISSUE TITLE
Diacritics and autocomplete

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pandora-postcorrect-app#39]
The accents problem seems partly fixed, but I still get some strange behaviours with auto-complete: sometimes it offers me choices, sometimes it doesn't. 

En fait, si je regarde plus en détail, il me semble que, quand je clique dans une case la première fois, pour éditer une valeur sauvegardée, l'auto-complétion se met en marche, mais, si je change d'avis, efface ce que j'ai tapé, et repart sur un nouveau lemme, ça ne me propose pas forcément de le compléter. Bizarre, mais pas forcément excessivement grave.

cf. #34  et #32

**Comment by PonteIneptique** [comment]
Potentiellement fixé dans #38

**Comment by PonteIneptique** [comment]
Tu peux check celle là ?

**Comment by Jean-Baptiste-Camps** [comment]
Super, ça marche ! C'est juste un poil plus lent (on peut pas tout avoir ;)

**Comment by PonteIneptique** [comment]
Fermons l'issue mais la lenteur ne doit pas venir de ça, sauf si ton pc a
15 ans.

**Comment by Jean-Baptiste-Camps** [comment]
si, parce qu'il me charge l'autocomplétion de l'intégralité des lemmes existants quand je n'ai encore rien tapé, ce qui ne se produisait pas avant.

**Comment by PonteIneptique** [comment]
Ah bah ça c'est un bug à régler par contre. Tu m'ouvre une petite issue
genre vérifier qu'il y a quelque chose dans le champ ? :)
