### ISSUE TITLE
Search functionnality over corpora

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora-postcorrect-app#50]
It would be great to be able to do a multiple field research (form, lemma, left_context, right_context, POS, morph) using wildcard if possible with editables rows.

Using the templates, I think it is a rather good first issues as it will make clear how the templates work in PPA as well as the routes and tests ;)

**Comment by MrGecko** [comment]
@PonteIneptique What do you mean by "editables rows" ?

**Comment by MrGecko** [comment]
@Jean-Baptiste-Camps @PonteIneptique  Which kind of combinatory and logical operator would you need to perform the search operations you want ?

At the moment, **LIKE** operations are possible (using * instead of the SQL %) and negations too with the **!** operator :

![image](https://user-images.githubusercontent.com/65418/40232406-ebe6601c-5a9e-11e8-95d5-aea9645fe13f.png)

![image](https://user-images.githubusercontent.com/65418/40232214-37d9bbc8-5a9e-11e8-9fe9-f5ca12082d04.png)

Is there any chance * and ! would appear as tokens ? In this case we may need to be able to comment them. An other way would be to use separated checkboxes to enable/disable unitary operators.

**Comment by MrGecko** [comment]
Also, I suggest to add the search feature directly within the Edit Tokens page (and not create a separate page like I've done as of today).

**Comment by Jean-Baptiste-Camps** [comment]
Ok, so, clearly, `!`, and perhaps sometimes `*` could be tokens, as they are corpora with POS annotation of punctuation (for instance BFM).

**Comment by PonteIneptique** [comment]
On peut dire au gens d'échapper ceux-ci au pire (`\!`) comme le prévoit @MrGecko non ?

**Comment by ArianePinche** [comment]
Bonjour, à mon avis, il serait bien de garder les pages séparées entre l'édition de token et la recherche pour éviter des confusions dans l'esprit de l'utilisateur du point de vue de l'utilisation, mais aussi de la lisibilité de la page. 
Pour les opérateurs, considérer que les différentes catégories sont liées par un `AND` permettrait d'éviter du bruit dans les résultats (situation actuelle, me semble-t-il ?). Enfin, introduire au sein des catégories des `OR` permettrait, je pense, d'étoffer un peu les requêtes : avec un `|` comme en xpath par exemple ?

**Comment by MrGecko** [comment]
Merci pour vos remarques. J'ai pris en compte l'échappement des opérateurs.
L'ajout d'un ```OR``` au sein d'une catégorie nécessiterait peut-être l'apport de la notion de groupes : 
```
      seint|saint
      s(a|e)int
      s(a|o(i|e))nt   -> sant, soint, soent, 
```
Ce qui reviendrait à réellement considérer les expressions comme des arbres contenant des opérateurs et des littéraux et c'est un poil plus complexe à réaliser :)
Ou alors on en considère que le premier et plus simple des trois exemples ci-dessus, sans groupe.

Qu'en pensez-vous (sachant qu'il faut prendre en compte les interactions de ```|``` avec ```!``` et ```*```) ?

**Comment by PonteIneptique** [comment]
Je pense que si on supporte `seint|saint`, c'est LARGEMENT suffisant pour la première version. :)

**Comment by PonteIneptique** [comment]
Note : avant que tu passes à l'implémentation utilisateur, on peut peut-être basculer ca sur la master en PR quand tu auras fini ? Ca permettra une derniere release avec cette fonctionnalité avant d'avoir le besoin de compte

**Comment by PonteIneptique** [comment]
Je te laisse l'honneur de fermer l'issue @MrGecko :D

**Comment by MrGecko** [comment]
Camarades, c'est avec la plus grande émotion que je clos cette issue.

**Comment by PonteIneptique** [comment]
@MrGecko en ce moment 
![](https://media.giphy.com/media/8UF0EXzsc0Ckg/giphy.gif)

Le reste de l'équipe

![](https://media.giphy.com/media/3o7TKrN4XDi4nnDh5K/giphy.gif)

Un petit troll ne fait pas mal ;)
