### ISSUE TITLE
Propriété `similar` et `changed` coûteuses

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora-postcorrect-app#64]
En comparant l'exécution de l'application sur la route `/corpus/<id>/tokens/edit?page=1&limit=1000` avec un corpus de 18k mots avec et sans la ligne https://github.com/hipster-philology/pandora-postcorrect-app/blob/dev/app/models/linguistic.py#L438 , le gain de performance est assez incroyable : 

On passe de 1703 ms d'execution à 12917 millisecondes...

Même chose pour changed qui impact de quelques secondes

**Comment by PonteIneptique** [comment]
Options : 
1. Supprimer cette info sur edit tokens (ce serait dommage)
2. Mise en cache (oui mais première exécution toujours lourde)
3. Pour `changed` **uniquement**, création d'une propriété dans la table afin d'éviter la sélection externe.
4. Trouver une meilleur manière de requêter...

**Comment by PonteIneptique** [comment]
Travail en cours ici https://github.com/hipster-philology/pandora-postcorrect-app/tree/performance-fix

**Comment by PonteIneptique** [comment]
Piste : https://stackoverflow.com/questions/1052148/group-by-count-function-in-sqlalchemy

**Comment by PonteIneptique** [comment]
Je n'arrive pas a ajouter un script de migration...

**Comment by PonteIneptique** [comment]
Juste une note (le score contient la création du corpus et login)

| limit=100   for 18k token corpus | limit=1000 for 18k token corpus |
| ---------------------------------------  | -------------------------------------- |
|  3.305190896987915                 |  16.40773742198944              |

Donc 1.61 second / 100 tokens (ce qui confirme bien https://github.com/hipster-philology/pandora-postcorrect-app/pull/66#issuecomment-437321489 ). Ce score est donc tout bonnement inacceptable.

**Comment by PonteIneptique** [comment]
Je vais donc continuer à voir ce que l'on peut faire...

**Comment by PonteIneptique** [comment]
Alors, la requête suivante :

```sql
SELECT
  wt.*,
  EXISTS(
    SELECT
      cr.id
    FROM
      change_record cr
    WHERE
      cr.word_token_id = wt.id
  ) AS changed,
  (
    SELECT
      COUNT(wt2.id)
    FROM
      word_token wt2
    WHERE
      wt2.corpus = wt.corpus
      AND wt2.form = wt.form
      AND wt2.id != wt.id
      AND  (
        wt2.lemma = wt.lemma
        OR wt2.POS = wt.POS
        OR wt2.morph = wt.morph
      )
  ) AS similar
FROM
  word_token wt
WHERE
  wt.corpus = '1'
ORDER BY
  wt.order_id
LIMIT
  100
```

**Sur une seule itération**

| Modifications éventuelles | SQLite | MySQL |
| ------------------------------- | ---------- | --------- |
| Complète | 125.05s | 1.30s |
| Sans similar | 0.03s | 0.11s |

**Comment by mestileryan** [comment]
Bonjour, j'ai reproduis les données grâce à @PonteIneptique et j'ai regardé un peu, le soucis vient clairement du SELECT imbriqué ici, de ce que je peux voir, c'est plus coûteux qu'un produit cartésien (ou bien une jointure comme ici)

Bref, concrètement, j'ai changé la requête et avec @PonteIneptique on a tenté de l'améliorer mais le but était d'intégrer wt2 dans la requête principale (j'ai essayé pour changed, mais ça marche pas forcément ni n'optimise beaucoup, vu que EXISTS c'est assez optimisé).

Voici la requête que j'ai :

```SQL
SELECT
  wt.*,
  EXISTS(
    SELECT
      cr.id
    FROM
      change_record cr
    WHERE
      cr.word_token_id = wt.id
  ) AS changed
  , count(*)-1 as similar
FROM
  word_token wt
  LEFT JOIN word_token wt2 on wt2.form = wt.form AND wt2.corpus = wt.corpus
WHERE
  wt.corpus = '1'
  AND (
    wt2.lemma = wt.lemma
    OR wt2.POS = wt.POS
    OR wt2.morph = wt.morph
  )
GROUP BY wt.id
ORDER BY
  wt.order_id
LIMIT
  100
```

On arrive à des performances d'environ 10 secondes sur les données entières avec SQLite
Notes : 
- LIMIT n'a AUCUN effet en terme d'exécution, il est là simplement pour l'affichage
- Il y a peut-être moyen de jouer avec les index, il faudrait que je me replonge dedans parce que j'ai pas réussi à avoir d'amélioration avec
- Je vois jusqu'à une amélioration de 50% sur le temps final en limitant les données sélectionnées (50% c'est en prenant que l'id, mais déjà en supprimant certaines données, y a ptet moyen d'améliorer un peu)
- Dommage que les procédure stockées ne soient pas dispo avec SQLite, on aurait peut-être pu créer une table dédiée juste pour cette requête (mais j'ai pas creusé du tout)... ^^

Voilà, bon courage !

**Comment by PonteIneptique** [comment]
Merci @mestileryan :D

**Comment by PonteIneptique** [comment]
Dans le push @b91567f  

**Create + Read 100 st token** (Moyenne sur 100 calls)

0. Situation initiale : `3.30s`
1. Modifications sur .similar en utilisant une requête différente (optimisée pour le count) : `3.05s` (`-0.25s`)
2. Retrait changed : `2.52s` (donc gain potentiel jusqu'à `0.53s` !)
3. `.changed` via exists : `2.72s` ; `-0.33s` par rapport à 1., `-0.55s` par rapport à situation initiale
4. `similar` enlevé : `1.98s` ( `-0.74s`)

**Comment by PonteIneptique** [comment]
Bien que ce soit plus bas, je propose que .similar ne soit plus affiché par défaut, mais qu'il soit "visible" après chargement. Qu'en pensent @Jean-Baptiste-Camps et @LucenceIng ?

**Comment by Jean-Baptiste-Camps** [comment]
Oui, j'ai aussi tendance à lire le nombre de cas similaires au fur et à mesure de la correction.

**Comment by PonteIneptique** [comment]
Je pense qu'on est passé sous la barre des 1s de chargement sur les pages tokens et on peut s'en satisfaire :) Maintenant, faut attendre nos joyeux @MrGecko et @architexte pour les PR et avoir leur avis :)

**Comment by PonteIneptique** [comment]
Fixed by #66 :D
