### ISSUE TITLE
Add session protection and "roles"

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora-postcorrect-app#9]
*Disclaimer : The way I kickstarted this app is for it to be used locally. But I kept possible its transformation to a full web application that could be publicly hosted. I will not develop this function myself, because this is not what I care directly about. If you like the app and are willing to put some time and energy, please think about implementing this*

- [x] Register an account
- [ ] Add a default account or Disable account system from manager (required for local quick use)
- [x] Login (Obviously)
- [x] Restrict access to corpora
- [x] Give access to other users

**Comment by MrGecko** [comment]
I'd like to detail here the role feature. Given two roles: admin & user 

**Admins can:**
- view all corpora
- add user / invite user / disable user (latter is not implemented yet)  
- give/delete access to everybody to all corpora
- view & update all users info
- edit tokens/lemma/... to all corpora

**Users can:**
- view all corpora it created or has been given access to
- give/delete access to everybody to all corpora it created or has been given access to
- view & update its own info
- edit tokens/lemma/... to all corpora it created or has been given access to

Should a standard user be able to remove its own accesses from a corpus ?

**Comment by Jean-Baptiste-Camps** [comment]
Should users be able to delete access to anybody on the corpora they just have been given access to? Or only the owner ?

**Comment by MrGecko** [comment]
@Jean-Baptiste-Camps  I suggest that:
- A user creating a corpus becomes its first owner
- Owners (and admin) can give / remove / share the ownership with other users.
- Owners (and admin) can give / remove rights access to a corpus to users 
- Other users can either access the corpus either not.

I consider having access to a corpus means you are free to edit the tokens & every part of its configuration

**Comment by PonteIneptique** [comment]
@MrGecko 
For the redis dependancy, no issue, I am sure we'll find something better later. Did you have a check on that ( https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-x-email-support ) ? Keep in mind I never had to implement this...

The only restriction I can see is that people should not be able to remove the last owner of a repository :)

**Comment by MrGecko** [comment]
Neat ! Quite simplier. I'll check around if I can use these plain old threads instead of Redis Queues.
So... Let me share with you how the role feature may look like !

**From an admin point of view:**
![31485841_1881145971920101_4554571667879231488_n](https://user-images.githubusercontent.com/65418/40729139-0db7aa98-642c-11e8-81bd-f9c8046c51ec.png)

**An owner would see the same screen:**
![capture d ecran_2018-05-30_17-05-02](https://user-images.githubusercontent.com/65418/40729201-2c69ba80-642c-11e8-98bc-e482eb351980.png)

**From the basic user point of view:**
![capture d ecran_2018-05-30_17-05-56](https://user-images.githubusercontent.com/65418/40729196-2a8dc8be-642c-11e8-8d79-aa701271a824.png)
(checkboxes are not empty but disabled... my theme fails to display the diff)

**Comment by PonteIneptique** [comment]
Nice :)
We really need to come up with a better name for PPA because that is a long name.

**Comment by Jean-Baptiste-Camps** [comment]
@MrGecko , Ok, the only part I'm worried about is:
Owners (and admin) can give / remove / share the ownership with other users.

But, it would perhaps be too much additional work to differentiate owners and 'write-access' users, that could edit tokens, etc., but not manage other users ?

Use case: I give an annotator access to my corpus, and I want her to be able to correct the tokens, edit lemma list, etc., but I do not want her to add new users I'm not aware of, or remove me of access to my own corpus.

Or maybe I just did not understood, and this is the difference between 'owner' and 'user' ;)

**Comment by MrGecko** [comment]
@Jean-Baptiste-Camps this is indeed the difference between owner and user (as illustrated :) )

**Comment by PonteIneptique** [comment]
Fixed by #56 and #58 open for the unchecked box :)
